shabados/docs

docusaurus.config.js, package-lock.json, package.json
Update docusaurus to latest version to enable [hideable sidebar](https://v2.docusaurus.io/docs/docs-introduction/#hideable-sidebar) 
**Deployment Preview:** https://shabad-os-docs-git-update-docusarus.saihaj.vercel.app
10 mins
@Harjot1Singh @bhajneet
=> build: update docusaururs

content/gurmukhi-utils/index.md
Transfer usage and API docs from [shabados/gurmukhi-utils](https://github.com/shabados/gurmukhi-utils)
**Deploy preview:** https://shabad-os-docs-git-gurmukh-utils.saihaj.vercel.app
@bhajneet
=> docs(gurmukhi-utils): transfer docs

content/community/coding-guidelines.md, content/community/how-to-contribute.md, content/community/index.md, content/community/project-management.md, content/community/support-and-feedback.md, src/pages.config.js, src/sidebars/community.js
Transfer contributing and project management docs from community files [wiki](https://github.com/shabados/.github/wiki)
40 minutes
**Deploy preview:** https://shabad-os-docs-git-community.saihaj.vercel.app
=> docs(community): transfer contributing and management docs from wiki

README.md
removes non-existing next release badge from readme
5 mins
@saihaj
=> docs: update readme release badges

docusaurus.config.js, src/css/custom.css
fix #13 
updates styles
before
after
- dark/light theme
- mobile devices
45-90 mins
Fix #13 
@saihaj
=> feat(frontend): update styles to be more modern

docusaurus.config.js, src/css/custom.css
brief_summary_plz
- none_whatsoever
nine_thousand_years
Fix #
@saihaj
=> feat(frontend): remove footer

src/css/custom.css
colors were not showing up properly
fix #31
=> fix(frontend): target css of sidebar appropriately

docusaurus.config.js
Adds info about algolia to config, removes products parent dropdown link, renames documentation to docs.
- none_whatsoever, need to upload to prod for further testing
15 mins
Fix #32 
@saihaj
=> build: configure docusaurus for algolia

src/css/custom.css
=> feat: make ToC more readable with a title and bolded active items

src/css/custom.css
seems rgba doesn't work on production, though it's fine on localhost -- testing
fix #37
15-30 mins researching, ultimately <5 mins of work
=> fix: use hexcode for border colors instead of rgba

src/css/custom.css
=> fix: change broken css from rgba to hex

content/community/project-management.md, content/database/index.md, content/database/installing-or-accessing.md, content/database/schema/bani_lines.md, content/database/schema/banis.md, content/database/schema/line_content.md, content/database/schema/line_types.md, content/database/schema/lines.md, content/database/schema/overview.md, content/database/schema/sections.md, content/database/schema/shabads.md, content/database/schema/sources.md, content/database/schema/subsections.md, content/database/schema/translation_sources.md, content/database/schema/translations.md, content/database/schema/transliterations.md, content/database/usage/index.md, content/presenter/guides/configuring-live-stream-captions.md, content/presenter/index.md, content/presenter/reference/url-endpoints.md, content/tutorials/index.md, content/tutorials/overlay/create-custom-theme.md, content/tutorials/overlay/get-started.md, src/pages/index.js
fix #54 
- npm run build
< 1 hour
Fix #54
=> fix: use static links for articles

docusaurus.config.js, package-lock.json, package.json, src/css/custom.css, src/pages/index.js
allows searching with algolia and adds a search bar to the home page hero
- locally tested to see search results, they worked
1 hour
=> fix: update algolia configuration

.github/workflows/ci.yml, .github/workflows/danger.yml, commitlint.config.js, dangerfile.js, package-lock.json, package.json
Continuation of #45
- build: add danger
- build: setup commitlint with danger
- ci: add danger
=> ci: setup danger js to lint PR titles

content/presenter/guides/configuring-live-stream-captions.md
adds an article for live streaming with streamlabs on iOS using the overlay from the desktop app.
- none_whatsoever
1 hour
Fix #59
Images didn't seem to add much to this tutorial, so I removed the ones I had. It might be better to add a YouTube video for this later and add a link to that in the article.
=> feat: add article for live streaming with streamlabs

content/database/source-material.md, src/css/custom.css
fixes various minor issues with css theming -- surprised so many of these exist, i'm sure learning more about ifm and having that project mature more in the future will help later
- light vs dark theme
- desktop vs mobile views
2 hours
Fix #60
=> fix: change minor thematic issues

content/presenter/guides/importing-an-overlay-theme.md, src/sidebars/presenter.js
Adds an article for users to learn how to import custom overlay themes.
- `npm run build`
10 min
=> feat: add an article on importing an overlay theme

content/presenter/guides/integrating-closed-captioning-in-zoom-meetings.md
brief_summary_plz
- none_whatsoever
nine_thousand_years
Fix #
=> fix: update steps in zoom article

content/community/index.md
=> fix: slack url

src/consts.js
=> fix: edit link url
